import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import SendMoneyForm from "../component/SendForm"

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>Welcome</h1>

        <ConnectButton
          accountStatus={{
            smallScreen: "avatar",
            largeScreen: "full",
          }}
          showBalance={{
            smallScreen: false,
            largeScreen: true,
          }}
        />
        
        <div className={styles.card}>
          <SendMoneyForm />
        </div>
      </main>

      <footer className={styles.footer}>
          Made with ❤️ by BlockChain DevTeam
      </footer>
    </div>
  );
};

export default Home;
